### ISSUE TITLE
hat szótag után kötőjellel írandó a központ

### ISSUE THREAD

**Issue by zelding** [papp-balazs/kutatokozpont#2]
Pl `Időpontfoglaláskutató` helyett `Időpontfoglalás-kutató`
Itt:
https://github.com/papp-balazs/kutatokozpont/blob/master/scripts.js#L25

Kicsit nézelődtem, természetesen a szótagszámolás nem triviális, ha lesz egy kis időm még, akkor majd forkolok, meg kísérletezgetek vele; eddig ezt találam - ugyan python - , de kezdetnek jó lehet
https://hu.tortoisetrades.com/490830-syllable-count-in-python-DWVJEB

**Comment by berdosi** [comment]
Én biztosan feltételezném, hogy magyarul van, és elég a magánhangzókat megszámolni. (Esetleg eleve odaraknám a főnevek után már a TXT fájlban… ☺)
```javascript
		const hyphenOrNot = (noun.length - noun.replace(/[űáéúőóüöíeuioa]/g, "").length) > 4 ? "-" : "";

		generatedResearchCenterElement.innerHTML = `${nationality}-Magyar ${noun}${hyphenOrNot}kutató Központ`;
```
Hátha van szofisztikáltabb ötleted, nem küldök PR-t. (Pl. a mostani korpuszban vannak dátumok számokkal, eleve kötőjeles szavak, többszavas kifejezések, meg egy-két idegen szó…)

**Comment by zelding** [comment]
túlgondoltam, mivel a névlista fix, szerintem bőven elég a megoldásod
